// ignore_for_file: equal_keys_in_map

import 'package:get/get.dart';

@override
class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "Nurse visit": "Nurse visit",
          "Doctor visit": "Doctor visit",
          "Virtual Consultation": "Virtual Consultation",
          "Vitamin IV drips and fluids": "Vitamin IV drips and fluids",
          "Laboratory": "Laboratory",
          "Our Services ": "Our Services ",
          "Appointments": "Appointments",
          "Accepted appointments": "Accepted appointments",
          "Contact": "Contact",
          "Contacts": "Contacts",
          "Contact us": "Contact us",
          "Family": "Family",
          "About Us": "About Us",
          "Your requests": "Your requests",
          "logout": "Logout",
          "Login": "Login",
          "Register": "Register",
          "Result upload": "Result Upload",
          "Upload Result": "Upload Result",
          "Name": "Name",
          "Email": "Email",
          "Email Address": "Email Address",
          "phone number": "phone number",
          "password": "password",
          "Register as a Service Provider": "Register as a Service Provider",
          "Designation": "Designation",
          "Register as a User": "Register as a User",
          "30% Discount for the first order":
              "30% Discount for the first order",
          "Please Select Your Designation": "Please Select Your Designation",
          "Harees": "Harees",
          "Your Account": "Your Account",
          "Settings": "Settings",
          "Logout": "Logout",
          "Completed Requests:": "Completed Requests:",
          "Search...": "Search...",
          "Search": "Search",
          "See result": "See result",
          "Something went wrong": "Something went wrong",
          "Loading": "Loading",
          "Accept Appointment": "Accept Appointment",
          "Are you sure?": "Are you sure?",
          "Yes": "Yes",
          "No": "No",
          "Joining as a Service Provider": "Joining as a Service Provider",
          "Name required": "Name required",
          "Email required": "Email required",
          "Password required": "Password required",
          "ID CARD Number": "ID CARD Number",
          "ID Number required": "ID Number required",
          "Email cannot be empty": "Email cannot be empty",
          "Password cannot be empty": "Password cannot be empty",
          "Not a provider?": "Not a provider?",
          "Register Now": "Register Now",
          "Upload Result here": "Upload Result here",
          "Success": "Success",
          "Appointment Accepted check your accepted appointments":
              "Appointment Accepted check your accepted appointments",
          "Service Type: Laboratory": "Service Type: Laboratory",
          "Service Type: Doctor Visit": "Service Type: Doctor Visit",
          "Service Type: Nurse Visit": "Service Type: Nurse Visit",
          "Join as a provider": "Join as a provider",
          "Join as a user": "Join as a user",
          "Contact Us": "Contact Us",
          "Enter your message": "Enter your message",
          "Submit": "Submit",
          "Services:": "Services:",
          "Services": "Services",
          "Your accepted requests:": "Your accepted requests:",
          "Service Type: Virtual Consultation":
              "Service Type: Virtual Consultation",
          "Service Type: Vitamin IV Drips And Fluids":
              "Service Type: Vitamin IV Drips And Fluids",
          "Not a member?": "Not a member?",
          "Account created successfully": "Account created successfully",
          "The email address is already in use by another account.":
              "The email address is already in use by another account.",
          "The password provided is too weak.":
              "The password provided is too weak.",
          "An error occurred while creating the account.":
              "An error occurred while creating the account.",
          "Error": "Error",
          "Already a member?": "Already a member?",
          "Let's login": "Let's login",
          "Current Location": "Current Location",
          "My Location": "My Location",
          "To proceed": "To proceed",
          "Kindly click on your address mentioned below":
              "Kindly click on your address mentioned below",
          "Are you sure you want to confirm":
              "Are you sure you want to confirm",
          "Confirm": "Confirm",
          "Cancel": "Cancel",
          "Address will appear here when you press the button":
              "Address will appear here when you press the button",
          "Our Services:": "Our Services:",
          "Other Services:": "Other Services:",
          "Pending appointments": "Pending appointments",
          "Your result": "Your result",
          "Upload Results": "Upload Results",
          "Arabic": "Arabic",
          "English": "English",
          "We accept Bupa, Tawuniya, MEDGULF, Malath and AlRajhi Takaful insurance for medicine.":
              "We accept Bupa, Tawuniya, MEDGULF, Malath and AlRajhi Takaful insurance for medicine.",
          "We accept Bupa, Tawuniya, MEDGULF, Malath and AlRajhi Takaful insurance for telemedicine.":
              "We accept Bupa, Tawuniya, MEDGULF, Malath and AlRajhi Takaful insurance for telemedicine.",
          "Virtual Medical Service": "Virtual Medical Service",
          "Virtual Consultations": "Virtual Consultations",
          "Select Location": "Select Location",
          'Home Visit Services': 'Home Visit Services',
          "Vitamin IV Drips": "Vitamin IV Drips",
          'More Services:': 'More Services',
          "Home": "Home",
          "Chats": "Chats",
          "Settings": "Settings",
          "More": "More",
          "About Harees": "About Harees",
          "Password": "Password",
          "Sign Up": "Sign Up",
          "Confirm Password": "Confirm Password",
          "Upload Profile Picture": "Upload Profile Picture",
          "Select from Gallery": "Select from Gallery",
          "Take a photo": "Take a photo",
          "Full Name": "Full Name",
          "Complete Your Profile": "Complete Your Profile",
          "Done!": "Done!",
          "Sign in": "Sign in",
          "Don't have an account?": "Don't have an account?",
          "Already a User?": "Already a User?",
          "Let's Login": "Let's Login",
          "Experience": "Experience",
          "Log in": "Log in",
          "Nurse Visit": "Nurse visit",
          "Doctor Visit": "Doctor visit",
          "Vitamin Drips": "Vitamin Drips",
          "We accept Bupa, Tawuniya, MEDGULD, Malath and Alrajhi Takaful insurance for telemedicine":
              "We accept Bupa, Tawuniya, MEDGULD, Malath and Alrajhi Takaful insurance for telemedicine",
          "Select the consultant": "Select the consultant",
          'Hello!': 'Hello!',
          'More Services': 'More Services',
          "Results": "Results",
          "FAQ's": "FAQ's",
          'Pending Appointments': 'Pending Appointments',
          "FAQ": "FAQ",
          "Login To Your Account": "Login To Your Account",
          "Or Sign In With? ": "Or Sign In With? ",
          "Mobile": "Mobile",
          "Create a new account?": "Create a new account?",
          "Virtual Medical Services": "Virtual Medical Services",
          " Link": "Link",
          "Select Lab": "Select Lab",
          "Confirmation": "Confirmation",
          "Are you sure you want to continue?":
              "Are you sure you want to continue?",
          "Select Date": "Select Date",
          "January": "January",
          "February": "February",
          "March": "March",
          "April": "April",
          "May": "May",
          "June": "June",
          "July": "July",
          "August": "August",
          "September": "September",
          "October": "October",
          "November": "November",
          "December": "December",
          "Select a Date": "Select a Date",
          "Confirm": "Confirm",
          "Today": "Today",
          "Any": "Any",
          "Male": "Male",
          "Female": "Female",
          "Harees Health:": "Harees Health:",
          "Laboratory Riyadh, Saudi Arabia": "Laboratory Riyadh, Saudi Arabia",
          "Navigating to Selected Details...":
              "Navigating to Selected Details...",
          "View Selected Details": "View Selected Details",
          "Excluding visit fee": "Excluding visit fee",
          "Proceed to Payment Details": "Proceed to Payment Details",
          "Payment Details": "Payment Details",
          "Laboratory": "Laboratory",
          "Zyad Faisal": "Zyad Faisal",
          "Riyadh, Saudi Arabia": "Riyadh, Saudi Arabia",
          "Add promo code here": "Add promo code here",
          "Apply": "Apply",
          "Use wallet balance": "Use wallet balance",
          "Pay with bank points": "Pay with bank points",
          "Select payment method": "Select payment method",
          "Cancellation policy": "Cancellation policy",
          "Apple Pay": "Apple Pay",
          "Split into 3 payments": "Split into 3 payments",
          "4 interest-free payments": "4 interest-free payments",
          "Card payments": "Card payments",
          "Price Breakup": "Price Breakup",
          "Selected test": "Selected test",
          "Labpratory Package": "Labpratory Package",
          "Amount Payable": "Amount Payable",
          "Checkout": "Checkout",
          "Selected Service": "Selected Service",
          "Components Included:": "Components Included:",
          "December, 2024": "December, 2024",
          "protein_test_urine": "Urine Total Protein Test",
          "protein_test_blood": "Blood Total Protein Test",
          "ldl_cholesterol_test": "LDL Cholesterol Test",
          "vitamin_b6_test": "Vitamin B6 Test",
          "typhoid_fever_test": "Typhoid Fever Test",
          "renal_filtration_rate_test": "Renal Filtration Rate Test",
          "occult_blood_test": "Occult Blood Test",
          "prostate_antigen_test": "Free Prostate Antigen Test",
          "progesterone_hormone_test": "Progesterone Hormone Test",
          "indirect_combs_test": "Indirect Coombs Test",
          "benign_protein_test_urine": "Benign Protein Test in Urine",
          "urinary_swab_test": "Urinary Swab Test",
          "urine_culture_test": "Urine Culture Test",
          "folic_acid_test": "Folic Acid Level Test",
          "lithium_level_blood_test": "Lithium Level in Blood Test",
          "triglycerides_blood_test": "Triglycerides Blood Test",
          "brain_peptide_natriuretic_test": "Brain Natriuretic Peptide Test",
          "magnesium_blood_test": "Magnesium Blood Test",
          "g6pd_enzyme_deficiency_test": "G6PD Enzyme Deficiency Test",
          "cortisol_blood_test": "Cortisol Blood Test",
          "creatinine_clearance_test": "Creatinine Clearance Test",
          "alt_liver_enzymes_test": "ALT Liver Enzyme Test",
          "hba1c_test": "HbA1c Test",
          "cholesterol_blood_test": "Cholesterol Blood Test",
          "hepatitis_b_surface_antigen_test":
              "Hepatitis B Surface Antigen Test",
          "ana_test": "Antinuclear Antibody (ANA) Test",
          "igg_immunoglobulin_test": "IgG Immunoglobulin Test",
          "creatinine_blood_test": "Creatinine Blood Test",
          "lactate_dehydrogenase_enzyme_test":
              "Lactate Dehydrogenase Enzyme Test",
          "testosterone_free_hormone_test": "Free Testosterone Hormone Test",
          "acid-fast_bacteria_resistance_test":
              "Acid-Fast Bacilli Resistance Test",
          "wbc_count_test": "White Blood Cell Count Test",
          "eosinophil_count_test": "Eosinophil Count Test",
          "acth_hormone_test": "ACTH Hormone Test",
          "lipase_enzyme_test": "Lipase Enzyme Test",
          "creatinine_urea_ratio_test": "Creatinine to Urea Ratio Test",
          "ggt_enzyme_test": "Gamma Glutamyl Transferase (GGT) Test",
          "acid_phosphatase_enzyme_test": "Acid Phosphatase Enzyme Test",
          "estradiol_e2_hormone_test": "Estradiol (E2) Hormone Test",
          "phenytoin_level_blood_test": "Phenytoin Level in Blood Test",
          "cardiac_kinase_enzyme_test": "Cardiac Creatine Kinase Enzyme Test",
          "ast_liver_enzymes_test": "AST Liver Enzyme Test",
          "iron_level_test": "Iron Level Test",
          "vitamin_b2_test": "Vitamin B2 Test",
          "corrected_calcium_test": "Corrected Calcium Test",
          "platelet_count_test": "Platelet Count Test",
          "ptt_test": "Partial Thromboplastin Time (PTT) Test",
          "rpr_syphilis_test": "RPR Syphilis Test",
          "schistosomiasis_test": "Schistosomiasis Test",
          "hiv_test": "HIV Test",
          "vitamin_a_test": "Vitamin A Test",
          "myoglobin_protein_blood_test": "Myoglobin Protein Blood Test",
          "thyroid_peroxidase_antibody_test":
              "Thyroid Peroxidase Antibody Test",
          "sodium_blood_test": "Sodium Blood Test",
          "hepatitis_a_antibody_test": "Hepatitis A Antibody Test",
          "vitamin_e_test": "Vitamin E Test",
          "citrulline_antibody_level_test": "Citrulline Antibody Level Test",
          "microalbumin_urine_test": "Microalbumin Urine Test",
          "bilirubin_level_test": "Bilirubin (Direct) Blood Test",
          "albumin_blood_test": "Albumin Blood Test",
          "lh_hormone_test": "LH Hormone Test",
          "prolactin_hormone_test": "Prolactin Hormone Test",
          "vitamin_b12_test": "Vitamin B12 Test",
          "syphilis_antibody_test": "Syphilis Antibody Test (Palladium)",
          "skin_biopsy": "Skin Biopsy",
          "herpes_virus_2_igm_test": "Herpes Virus 2 (IgM) Test",
          "cmv_igm_antibody_test": "CMV IgM Antibody Test",
          "zinc_blood_test": "Zinc Blood Test",
          "h_pylori_breath_test": "H. Pylori Breath Test",
          "ige_total_immunoglobulin_test": "Total IgE Immunoglobulin Test",
          "tb_test_tr": "Tuberculosis Test",
          "alk_phosphatase_enzyme_test": "Alkaline Phosphatase Enzyme Test",
          "09:00 am": "9:00 am",
          "10:00 am": "10:00 am",
          "11:00 am": "11:00 am",
          "12:00 pm": "12:00 pm",
          "1:00 pm": "1:00 pm",
          "02:00 pm": "02:00 pm",
          "04:00 pm": "04:00 pm",
          "05:00 pm": "05:00 pm",
          "06:00 pm": "06:00 pm",
          "Select Packages": "Select Packages",
          "Selected item": "Selected item",
          "Continue": "Continue",
          "Your location": "Your location",
          "About This Package": "About This Package",
          "Care about you and your family": "Care about you and your family",
          "Components Included": "Components Included",
          "Select": "Select",
          "Step ": "Step ",
          "of": "of",
          "Cart Items": "Cart Items",
          "Amount payable": "Amount payable",
          "Qty :": "Qty :",
          "Your Package tests": "Your Package tests",
          "SAR": "SAR",
          "Date of birth": "Date of birth",
          "Gender": "Gender",
          "Patient Info": "Patient Info",
          "Save": "Save",
          "Lab Tests": "Lab Tests",
          "and Packages": "and Packages",
          "Body function or health concern": "Body function or health concern",
          "Full body": "Full body",
          "Diabetes": "Diabetes",
          "View all Packages": "View all Packages",
          "Most helpful packages": "Most helpful packages",
          "Cholesterol": "Cholesterol",
          "Starting": "Starting",
          "Next": "Next",
          "We Sent OTP code to verify your number":
              "We Sent OTP code to verify your number",
          "Enter Phone Number": "Enter Phone Number",
          "Enter": "Enter",
          "Instructions": "Instructions",
          "Your healthcare just got easier and closer! get trusted home care services from certified providers through our app.":
              "Your healthcare just got easier and closer! get trusted home care services from certified providers through our app.",
          "Your peace of mind starts here!": "Your peace of mind starts here!",
          "Our Services": "Our Services",
          "Doctor Consultation": "Doctor Consultation",
          "Tests & IV Vitamins": "Tests & IV Vitamins",
          "Meetings": "Meetings",
          "Tests": "Tests",
          "Harees": "Harees",
          "Create Your Account": "Create Your Account",
          "Patient Record": "Patient Record",
          "All packages": "All packages",
          "Individual Packages": "Individual Packages",
          "General Packages": "General Packages",
          "ID/Iqama Number": "Meetings",
        },
        "ar_AE": {
          "Harees": "Harees",
          "Create Your Account": "تسجيل الدخول إلى حسابك",
          "Patient Record": "سجل المريض",
          "All packages": "جميع الباقات",
          "Individual Packages": "الحزم الفردية",
          "General Packages": "الحزم العامة",
          "Tests": "المحاليل الوريدية",
          "ID/Iqama Number": "رقم الهوية/الإقامة",
          "Meetings": "الاجتماعات",
          "Tests & IV Vitamins": "التحاليل و المحاليل الوريدية",
          "Doctor Consultation": "استشارة طبيب عن بعد",
          "Our Services": "خدماتنا",
          "Your peace of mind starts here!": "احة البال تبدأ هنا!",
          "Your healthcare just got easier and closer! get trusted home care services from certified providers through our app.":
              "رعايتك الصحية أصبحت أسهل وأقرب! عبر تطبيقنا، نوفر لك خدمات منزلية متميزة من نخبة مقدمي الرعاية الصحية المعتمدين، لتعيش بصحة وراحة.  ",
          "Instructions": "إرشادات",
          "Enter": "أدخل",
          "We Sent OTP code to verify your number":
              "لقد أرسلنا لك رمز OTP للتحقق من رقمك.",
          "Next": "التالي",
          "Enter Phone Number": "أدخل رقم الهاتف",
          "Starting": "بداية",
          "View all Packages": "عرض جميع الباقات",
          "Most helpful packages": "الحزم الأكثر فائدة",
          "Cholesterol": "الكوليسترول",
          "Diabetes": "السكري",
          "Full body": "الجسم بالكامل",
          "Body function or health concern": "وظيفة الجسم أو مشكلة صحية",
          "and Packages": "والحزم",
          "Lab Tests": "الاختبارات المعملية",
          "Save": "يحفظ",
          "Patient Info": "معلومات المريض",
          "Gender": "جنس",
          "Date of birth": "تاريخ الميلاد",
          "SAR": "ريال",
          "Your Package tests": "لعناصر المختارة",
          "Qty :": "العدد:",
          "Amount payable": "المبلغ المستحق",
          "Cart Items": "عناصر السلة",
          "of": "ar_AE",
          "Step ": " خطوة",
          "Select": "اختر",
          "Components Included": "المكونات",
          "Care about you and your family": "حريص عليك وعلى عائلتك",
          "About This Package": "عن الباقة",
          "Your location": "موقعك",
          "Continue": "متابعة",
          "Selected item": "عرض السلة",
          "Select Packages": "اختر الباقات",
          "09:00 am": "9:00 صباحا",
          "10:00 am": "10:00 صباحا",
          "11:00 am": "11:00 صباحا",
          "12:00 pm": "12:00 مساءً",
          "1:00 pm": "1:00 مساءً",
          "02:00 pm": "02:00 مساءً",
          "04:00 pm": "04:00 مساءً",
          "05:00 pm": "05:00 مساءً",
          "06:00 pm": "06:00 مساءً",
          "December, 2024": "ديسمبر 2024",
          "protein_test_urine": "فحص البروتين الكلي في البول",
          "protein_test_blood": "فحص البروتين الكلي في الدم",
          "ldl_cholesterol_test": "فحص الكوليسترول الضار (LDL)",
          "vitamin_b6_test": "فحص فيتامين B6",
          "typhoid_fever_test": "فحص حمى التيفوئيد",
          "renal_filtration_rate_test": "فحص معدل الترشيح الكلوي النسبي",
          "occult_blood_test": "فحص الدم المختفي في البراز",
          "prostate_antigen_test": "تحليل مستضد البروستاتا النوعي الحر",
          "progesterone_hormone_test": "فحص هرمون البروجسترون",
          "indirect_combs_test": "تحليل كومبس الغيرمباشر",
          "benign_protein_test_urine": "تحليل بروتينات بنس جونس في البول",
          "urinary_swab_test": "اختبار مسحة افرازات مجرى البول",
          "urine_culture_test": "اختبار مزرعة البول",
          "folic_acid_test": "فحص مستوى حمض الفوليك في الجسم",
          "lithium_level_blood_test": "فحص مستوى الليثيوم في الدم",
          "triglycerides_blood_test": "فحص الدهون الثلاثية في الدم",
          "brain_peptide_natriuretic_test":
              "تحليل البيبتيد الدماغي المدر للصوديوم",
          "magnesium_blood_test": "تحليل المغنيسيوم في الدم",
          "g6pd_enzyme_deficiency_test":
              "فحص اعتلال انزيمات كريات الدم الحمراء (نقص انزيم التفول) G6PD",
          "cortisol_blood_test": "فحص الكورتيزول في الدم",
          "creatinine_clearance_test": "تحليل تصفية الكرياتينين",
          "alt_liver_enzymes_test": "فحص أنزيمات الكبد (ALT)",
          "hba1c_test": "فحص السكر التراكمي",
          "cholesterol_blood_test": "فحص مستوى الكوليسترول في الدم",
          "hepatitis_b_surface_antigen_test":
              "اختبار المستضد السطحي لالتهاب الكبد ب",
          "ana_test": "تحليل الأجسام المضادة للنواة (ANA)",
          "igg_immunoglobulin_test": "تحليل الغلوبولين المناعي IGG",
          "creatinine_blood_test": "فحص الكرياتينين في الدم",
          "lactate_dehydrogenase_enzyme_test":
              "فحص إنزيم نازع هيدروجين اللاكتات",
          "testosterone_free_hormone_test": "فحص هرمون التستوستيرون الحر",
          "acid-fast_bacteria_resistance_test":
              "اختبار مقاومة البكتيريا العصِيّة للحمض",
          "wbc_count_test": "عدد كرات الدم البيضاء (WBC)",
          "eosinophil_count_test": "عد كلي للأزينوفيل",
          "acth_hormone_test": "فحص الهرمون الموجه للغدة الكظرية ACTH",
          "lipase_enzyme_test": "فحص انزيم الليبيز",
          "creatinine_urea_ratio_test": "قياس نسبة الكرياتينين الى اليوريا",
          "ggt_enzyme_test": "فحص أنزيم ناقلة الغاما غلوتاميل",
          "acid_phosphatase_enzyme_test": "انزيم الفوسفاتيز الحمضي",
          "estradiol_e2_hormone_test": "فحص هرمون الاستراديول E2",
          "phenytoin_level_blood_test": "فحص مستوى الفينوتوين في الجسم",
          "cardiac_kinase_enzyme_test":
              "فحص قياس كمية إنزيم كاينيز الكرياتين القلبي",
          "ast_liver_enzymes_test": "فحص أنزيمات الكبد (AST)",
          "iron_level_test": "فحص نسبة الحديد",
          "vitamin_b2_test": "فحص فيتامين B2",
          "corrected_calcium_test": "تحليل الكالسيوم المصحح",
          "platelet_count_test": "فحص تعداد الصفائح الدموية",
          "ptt_test": "اختبار وقت الثرومبو بلاستين الجزئي (PTT)",
          "rpr_syphilis_test": "تحليل الزهري RPR",
          "schistosomiasis_test": "اختبار البلهاريسيا",
          "hiv_test": "فحص فيروس نقص المناعة الايدز",
          "vitamin_a_test": "فحص فيتامين A",
          "myoglobin_protein_blood_test": "تحليل بروتين مايوجلوبين في الدم",
          "thyroid_peroxidase_antibody_test":
              "اختبار الأجسام المضادة للبيروكسيداز الدرقي",
          "sodium_blood_test": "فحص الصوديوم في الدم",
          "hepatitis_a_antibody_test": "تحليل الأجسام المضادة لالتهاب الكبد أ",
          "vitamin_e_test": "فحص فيتامين E",
          "citrulline_antibody_level_test":
              "فحص مستوى الأجسام المضادة للسيترولين",
          "microalbumin_urine_test": "اختبار الميكرو ألبومين في البول",
          "bilirubin_level_test":
              "تحليل مستوى البيليروبين ( الصفراء المباشرة ) في الدم",
          "albumin_blood_test": "تحليل البومين في الدم",
          "lh_hormone_test": "تحليل هرمون ال اتش (LH)",
          "prolactin_hormone_test": "فحص هرمون الحليب",
          "vitamin_b12_test": "فحص فيتامين ب 12",
          "syphilis_antibody_test": "تحليل الزهري للاجسام المضادة للبلاديوم",
          "skin_biopsy": "خزعة الجلد",
          "herpes_virus_2_igm_test": "فحص فيروس الهربس 2 IGM",
          "cmv_igm_antibody_test":
              "فحص الأجسام المضادة لفيروس المضخم للخلايا IGM",
          "zinc_blood_test": "فحص مستوى الزنك في الدم",
          "h_pylori_breath_test": "فحص جرثومة المعدة بالنفس",
          "ige_total_immunoglobulin_test": "تحليل الغلوبولين المناعي الكلي IGE",
          "tb_test_tr": "فحص الكونتيفيرون (السل)",
          "alk_phosphatase_enzyme_test": "تحليل انزيم الفوسفاتيز القلوي",
          "Components Included:": "المكونات المتضمنة:",
          "Selected Service": "الخدمة المختارة",
          "Checkout": "الدفع",
          "Amount Payable": "المبلغ المستحق الدفع",
          "Labpratory Package": "حزمة المختبر",
          "Selected test": "الاختبار المختار",
          "Price Breakup": "تقسيم السعر",
          "Card payments": "مدفوعات البطاقة",
          "4 interest-free payments": "4 دفعات بدون فوائد",
          "Split into 3 payments": "مقسمة إلى 3 دفعات",
          "Apple Pay": "آبل باي",
          "Cancellation policy": "سياسة الإلغاء",
          "Select payment method": "حدد طريقة الدفع",
          "Pay with bank points": "الدفع باستخدام نقاط البنك",
          "Use wallet balance": "استخدم رصيد المحفظة",
          "Apply": "يتقدم",
          "Add promo code here": "أضف رمز الترويج هنا",
          "Riyadh, Saudi Arabia": "الرياض، المملكة العربية السعودية",
          "Zyad Faisal": "زياد فيصل",
          "Laboratory": "معمل",
          "Payment Details": "تفاصيل الدفع",
          "Proceed to Payment Details": "انتقل إلى تفاصيل الدفع",
          "Excluding visit fee": "باستثناء رسوم الزيارة",
          "View Selected Details": "عرض التفاصيل المحددة",
          "Navigating to Selected Details...":
              "الانتقال إلى التفاصيل المحددة...",
          "Laboratory Riyadh, Saudi Arabia":
              "المختبر الرياض، المملكة العربية السعودية",
          "Harees Health:": "صحة الهريس:",
          "Female": "أنثى",
          "Male": "ذكر",
          "Any": "أي",
          "Today": "اليوم",
          "Confirm": "يتأكد",
          "Select a Date": "حدد تاريخًا",
          "January": "يناير",
          "February": "فبراير",
          "March": "يمشي",
          "April": "ابريل",
          "May": "يمكن",
          "June": "يونيو",
          "July": "يوليو",
          "August": "أغسطس",
          "September": "سبتمبر",
          "October": "أكتوبر",
          "November": "نوفمبر",
          "December": "ديسمبر",
          "Select Date": "حدد التاريخ",
          "Are you sure you want to continue?":
              "هل أنت متأكد أنك تريد المتابعة؟",
          "Confirmation": "تأكيد",
          "Select Lab": "حدد معملًا",
          " Link": "وصلة",
          "Virtual Medical Services": "الخدمات الطبية الافتراضية",
          "Create a new account?": "إنشاء حساب جديد؟",
          "Mobile": "متحرك",
          "Or Sign In With? ": " أو تسجيل الدخول مع؟",
          "Login To Your Account": "تسجيل الدخول إلى حسابك",
          "Nurse visit": "زيارة تمريض",
          "Doctor visit": "زيارة طبيب",
          "Virtual Consultation": "استشارة طبيب عن بعد",
          "Laboratory": " الفحوصات",
          "Vitamin IV drips and fluids": "المحاليل والسوائل",
          "Our Services ": " خدماتنا ",
          "Appointments": "المواعيد",
          "Accepted appointments": "المواعيد المقبولة",
          "Contact": "اتصل بنا",
          "Family": "عائلة",
          "About Us": "من نحن",
          "Your requests": "طلباتك",
          "logout": "تسجيل خروج",
          "Login": "تسجيل الدخول",
          "Register": "تسجيل",
          "Result upload": "تحميل نتيجة",
          "Upload Result": "تحميل نتيجة",
          "Name": "الاسم",
          "Email": "البريد الالكتروني",
          "phone number": "رقم الهاتف",
          "password": "كلمة المرور",
          "Register as a Service Provider": "تسجيل كمزود خدمة",
          "Designation": "التعيين",
          "Register as a User": "تسجيل كمستخدم",
          "30% Discount for the first order": "خصم 30٪ على الطلب الأول",
          "Please Select Your Designation": "الرجاء تحديد التعيين الخاص بك",
          "Harees": "حريص",
          "Your Account": "الحساب الخاص بك",
          "Settings": "إعدادات",
          "Logout": "تسجيل خروج",
          "Completed Requests:": "الطلبات المكتملة:",
          "Search...": "ابحث...",
          "Search": "ابحث",
          "See result": "انظر النتيجة ",
          "Something went wrong": "هناك خطأ ما",
          "Loading": "تحميل",
          "Accept Appointment": "قبول الموعد",
          "Are you sure?": "هل انت متأكد؟",
          "Yes": "نعم",
          "No": "لا",
          "Joining as a Service Provider": "الانضمام كمقدم خدمة",
          "Name required": "الاسم مطلوب",
          "Email required": "البريد الالكتروني مطلوب",
          "Password required": "كلمة المرور مطلوبة",
          "ID CARD Number": "رقم بطاقة الهوية",
          "ID Number required": "رقم الهوية مطلوب",
          "Email cannot be empty": "لا يمكن ترك البريد الالكتروني فارغ",
          "Password cannot be empty": "لا يمكن ترك كلمة المرور فارغة",
          "Not a provider?": "ليس مزود؟",
          "Register Now": "سجل الان",
          "Upload Result here": "تحميل نتيجتك هنا",
          "Success": "نجاح",
          "Appointment Accepted check your accepted appointments":
              "تم قبول الموعد الرجاء التحقق من مواعيدك المقبولة",
          "Service Type: Laboratory": "نوع الخدمة: مختبر",
          "Service Type: Doctor Visit": "نوع الخدمة: زيارة طبيب",
          "Service Type: Nurse Visit": "نوع الخدمة: زيارة ممرض",
          "Join as a provider": "انضم كمقدم للخدمة",
          "Join as a user": "انضم كمستخدم",
          "Contact Us": "اتصل بنا",
          "Enter your message": "ادخل رسالتك",
          "Submit": "ارسال",
          "Services:": "الخدمات:",
          "Services": "الخدمات",
          "Your accepted requests:": "طلباتك المقبولة:",
          "Service Type: Virtual Consultation": "نوع الخدمة: استشارة فعالة",
          "Service Type: Vitamin IV Drips And Fluids":
              "نوع الخدمة: نقط وسوائل فيتامين الرابع",
          "Not a member?": "ليس عضو؟",
          "Account created successfully": "الحساب اقيم بنجاح",
          "The email address is already in use by another account.":
              "عنوان البريد الإلكتروني قيد الاستخدام بالفعل من قبل حساب آخر.",
          "The password provided is too weak.":
              "كلمة المرور المقدمة ضعيفة جدًا.",
          "An error occurred while creating the account.":
              "حدث خطأ اثناء انشاء الحساب.",
          "Error": "خطأ",
          "Already a member?": "عضوا فعلا؟",
          "Let's login": "دعونا تسجيل الدخول",
          "Current Location": "موقعك الحالي",
          "My Location": "موقعي",
          "To proceed": "للمتابعة",
          "Kindly click on your address mentioned below":
              "يرجى النقر على العنوان المذكورة ادناه",
          "Are you sure you want to confirm": "هل انت متأكد من تأكيد",
          "Confirm": "تأكيد",
          "Cancel": "الغاء",
          "Address will appear here when you press the button":
              "سيظهر العنوان هنا عند الضغط على الزر",
          "Our Services:": "خدماتنا:",
          "Other Services:": "خدمات اخرى:",
          "Pending appointments": "مواعيد معلقة",
          "Your result": "نتيجتك",
          "Upload Results": "تحميل نتيجتك",
          "Arabic": "العربية",
          "English": "English",
          "We accept Bupa, Tawuniya, MEDGULF, Malath and AlRajhi Takaful insurance for medicine.":
              "نقبل تأمين بوبا والتعاونية وميدغلف وملاذ وتكافل الراجحي للأدوية.",
          "We accept Bupa, Tawuniya, MEDGULF, Malath and AlRajhi Takaful insurance for telemedicine.":
              "نحن نقبل التأمين التكافلي من بوبا والتعاونية وميدغلف وملاذ والراجحي للتطبيب عن بعد.",
          "Virtual Medical Service": "خدمات الطب الفعالة",
          "Virtual Consultations": "استشارات فعالة",
          "Select Location": "اختر الموقع",
          'Home Visit Services': 'خدمات زيارة المنزل',
          "Vitamin IV Drips": "نقط وسوائل فيتامين الرابع",
          'More Services:': 'خدمات اخرى',
          "Home": "الرئيسية",
          "Chats": "المحادثات",
          "Settings": "الاعدادات",
          "More": "المزيد",
          "About Harees": "عن حريص",
          "Contacts": "اتصل بنا",
          "Contact us": "اتصل بنا",
          "Email Address": "البريد الالكتروني",
          "Password": "كلمة المرور",
          "Sign Up": "اشتراك",
          "Confirm Password": "تأكيد كلمة المرور",
          "Upload Profile Picture": "تحميل صورة الملف الشخصي",
          "Select from Gallery": "تحديد من المعرض",
          "Take a photo": "التقط صورة",
          "Full Name": "الاسم الكامل",
          "Complete Your Profile": "اكمل ملفك الشخصي",
          "Done!": "تم!",
          "Sign in": "تسجيل الدخول",
          "Don't have an account?": "ليس لديك حساب؟",
          "Already a User?": "عضوا فعلا؟",
          "Let's Login": "دعونا تسجيل الدخول",
          "Experience": "الخبرة",
          "Log in": "تسجيل الدخول",
          "Nurse Visit": "زيارة الناشئ",
          "Doctor Visit": "زيارة الطبيب",
          "Vitamin Drips": "نقط وسوائل فيتامين",
          "We accept Bupa, Tawuniya, MEDGULF, Malath and AlRajhi Takaful insurance for telemedicine.":
              "نحن نقبل التأمين التكافلي من بوبا والتعاونية وميدغلف وملاذ والراجحي للتطبيب عن بعد.",
          "Select the consultant": "اختر المرسل",
          'Hello!': "!مرحبا",
          'More Services': 'خدمات اخرى',
          "Results": "النتائج",
          "FAQ's": "التعليمات",
          'Pending Appointments': 'المواعيد المعلقة',
          "FAQ": "التعليمات",
        }
      };
}
